#
# Makefile for ALSA
# Copyright (c) 2001 by Jaroslav Kysela <perex@suse.cz>
#

snd-vx-lib-objs := vx_core.o vx_hwdep.o vx_pcm.o vx_mixer.o vx_cmd.o vx_uer.o

obj-$(CONFIG_SND_VXPOCKET) += snd-vx-lib.o
obj-$(CONFIG_SND_VXP440) += snd-vx-lib.o
obj-$(CONFIG_SND_VX222) += snd-vx-lib.o

