O_TARGET	:= cpu.o

obj-y	+=	amd.o
obj-y	+=	cyrix.o
obj-y	+=	centaur.o
obj-y	+=	transmeta.o
obj-y	+=	intel.o
obj-y	+=	rise.o
obj-y	+=	nexgen.o
obj-y	+=	umc.o

obj-y	+=	common.o
obj-y	+=	proc.o

include $(TOPDIR)/Rules.make
