
obj-$(CONFIG_SCSI_LPFCDD) := lpfcdd.o
lpfcdd-objs := lpfc_core.o core.o prod_linux.o lpfcLINUXfcp.o

obj-$(CONFIG_SCSI_LPFNDD) += lpfndd.o
lpfndd-objs := lpfcLINUXlan.o

EXTRA_CFLAGS += -Idrivers/scsi
