#
# Makefile for the 'freesync' sub-module of DAL.
#

FREESYNC = freesync.o

AMD_DAL_FREESYNC = $(addprefix $(AMDDALPATH)/modules/freesync/,$(FREESYNC))
#$(info ************  DAL-FREE SYNC_MAKEFILE ************)

AMD_DAL_FILES += $(AMD_DAL_FREESYNC)
