#
# Makefile for SuperH-specific library files..
#

L_TARGET = lib.a
obj-y  = delay.o memcpy.o memset.o memmove.o memchr.o old-checksum.o \
	 checksum.o strcasecmp.o strlen.o

include $(TOPDIR)/Rules.make
