#
# Makefile for the mouse drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_BITSY)	+= h3600_ts_input.o
obj-$(CONFIG_TOUCHSCREEN_GUNZE)	+= gunze.o

# The global Rules.make.

include $(TOPDIR)/Rules.make
