#
# Makefile for Etrax-specific library files..
#

L_TARGET = lib.a

EXTRA_AFLAGS := -traditional

obj-y  = checksum.o checksumcopy.o string.o usercopy.o memset.o csumcpfruser.o

include $(TOPDIR)/Rules.make
