# Makefile for the CAPI hardware drivers

# The target object and module list name.

O_TARGET	:= built-in.o

# Object files in subdirectories

mod-subdirs			:= avm
obj-$(CONFIG_CAPI_AVM)		+= avm/

# The global Rules.make.

include $(TOPDIR)/Rules.make
