#
# Makefile for the Linux hfs filesystem routines.
#

obj-$(CONFIG_HFS_FS) += hfs.o

hfs-objs := balloc.o bdelete.o bfind.o bins_del.o binsert.o bitmap.o bitops.o \
	    bnode.o brec.o btree.o catalog.o dir.o dir_cap.o dir_dbl.o \
	    dir_nat.o extent.o file.o file_cap.o file_hdr.o inode.o mdb.o \
            part_tbl.o string.o super.o sysdep.o trans.o version.o
