#
# Makefile for the linux MPC4xx ppc-specific parts 
#

O_TARGET 		:= 4xx_io.o

#obj-y			:=

obj-$(CONFIG_STB_KB)			+= stb_kb.o
obj-$(CONFIG_SERIAL_SICC)		+= serial_sicc.o
 
include $(TOPDIR)/Rules.make
