#!/bin/bash


if [ $# = "0" ] ; then
	echo
#	echo "usage: $0 <module_to_sign> <key_name>"
	echo "usage: $0 <module_to_sign>"
	echo
	exit 1
fi

module=$1
#key=$2

# strip out only the sections that we care about
./mod $module $module.out

# sign the sections
gpg --no-greeting -sb $module.out
## sha1 the sections
#sha1sum $module.out | awk "{print \$1}" > $module.sha1
#
## encrypt the sections
#gpg --no-greeting -e -o - -r $key $module.sha1 > $module.crypt

# add the encrypted data to the module
#objcopy --add-section module_sig=$module.crypt $module $module.sign
objcopy --add-section module_sig=$module.out.sig $module $module.sign

