#
# Makefile for the 'connector' sub-component of DAL.
# It provides the control and status of HW connectors blocks.


CONNECTOR = connector.o connector_signals.o

AMD_DAL_CONNECTOR = $(addprefix $(AMDDALPATH)/connector/,$(CONNECTOR))

AMD_DAL_FILES += $(AMD_DAL_CONNECTOR)
