.\" Copyright (c) 2002 Broadcom Corporation
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation.
.\"
.\" bcm4400.4,v 2.0 
.\"
.TH BCM4400 4 "03/25/02" "Broadcom Corporation"
.\"
.\" NAME part
.\"
.SH NAME
bcm4400 \- Broadcom BCM4400 series Ethernet device driver
.\"
.\" SYNOPSIS part
.\"
.SH SYNOPSIS
.B insmod bcm4400.o
.RB [ line_speed=\c
.IR n,... ]
.RB [ auto_speed=\c
.IR n,... ]
.RB [ full_duplex=\c
.IR n,... ]
.RB [ rx_flow_control=\c
.IR n,... ]
.RB [ tx_flow_control=\c
.IR n,... ]
.RB [ auto_flow_control=\c
.IR n,... ]
.RB [ tx_pkt_desc_cnt=\c
.IR n,... ]
.RB [ rx_pkt_desc_cnt=\c
.IR n,... ]
.RB [ enable_wol=\c
.IR n,... ]
.\"
.\" DESCRIPTION part
.\"
.SH DESCRIPTION
.I bcm4400
is the low-level device driver for the Broadcom
.B BCM4400
series PCI Ethernet NIC. The driver has been tested
on most 2.4.x kernels up to 2.4.20 for i386 systems only.
.PP
The driver supports up to 16 NICs and allocates the next available ethernet
device (eth0..eth#) for each NIC found. The driver is available as a loadable
module at this point. The loadable module binary
\fBbcm4400.o\fP is installed in the following path:
.PP
2.2.x kernels:
.RS
/lib/modules/<kernel_version>/net/bcm4400.o
.RE
.PP
2.4.x kernels:
.RS
/lib/modules/<kernel_version>/kernel/drivers/net/bcm4400.o
.RE
.PP

Refer to various Linux documentations
on how to configure network protocol and address.
.\"
.\" PARAMETER part
.\"
.SH PARAMETERS
Optional parameters for the driver can be supplied as command line arguments 
to the insmod command. These parameters can also be set in the file
/etc/modules.conf (see the man page for modules.conf). These parameters take
the form
.PP
.B <parameter>=n1[,n2,...]
.PP
where the multiple values n1,n2,... are for multiple NICs installed in the
system.
.PP
Note that default or other meaningful values will be used when invalid values
are selected. Some combinations of parameters may conflict and lead to
failures. The driver cannot detect all such conflicting combinations.
.PP
All the parameters are listed below.
.TP
.B line_speed
Selects the line speed of the link. This parameter is used together with
\fBfull_duplex\fP and \fBauto_speed\fP to select the speed and
duplexity of the link and the setting of autonegotiation. The valid values are:
.RS
.TP
.B 0
Autonegotiate for highest speed supported by link partner (default)
.TP
.B 10
10 Mbps
.TP
.B 100
100 Mbps
.PP
If \fBline_speed\fP is set to \fB10\fP or \fB100\fP,
the NIC will autonegotiate for
the selected speed (and selected duplexity) if \fBauto_speed\fP is set to
\fB1\fP. If \fBauto_speed\fP is set to \fB0\fP, the selected speed and
duplexity will be set without autonegotiation. 
.RE
.TP
.B auto_speed
Enables or disables autonegotiation. The valid values are:
.RS
.TP
.B 0
Autonegotiation disabled
.TP
.B 1
Autonegotiation enabled (default)
.PP
Note that this parameter is ignored and assumed \fB1\fP if \fBline_speed\fP is
set to \fB0\fP.
.RE
.TP    
.B full_duplex
Selects the duplexity of the link. This paramter is used together with
\fBline_speed\fP to select the speed and duplexity of the link. Note that this
parameter is ignored if \fBline_speed\fP is \fB0\fP. The valid values are:
.RS
.TP
.B 0
half duplex
.TP
.B 1
full duplex (default)
.RE
.TP
.B rx_flow_control
Enables or disables receiving flow control (pause) frames. This parameter
is used together with \fBauto_flow_control\fP. The valid values are:
.RS
.TP
.B 0
pause receive disabled (default)
.TP
.B 1
pause receive enabled if \fBauto_flow_control\fP is set to \fB0\fP, or pause
receive advertised if \fBauto_flow_control\fP is set to \fB1\fP
.RE
.TP
.B tx_flow_control
Enables or disables transmitting flow control (pause) frames. This parameter
is used together with \fBauto_flow_control\fP. The valid values are:
.RS
.TP
.B 0
pause transmit disabled (default)
.TP
.B 1
pause transmit enabled if \fBauto_flow_control\fP is set to \fB0\fP, or pause
transmit advertised if \fBauto_flow_control\fP is set to \fB1\fP
.RE
.TP
.B auto_flow_control
Enables or disables autonegotiation of flow control. This parameter is used
together with \fBrx_flow_control\fP and \fBtx_flow_control\fP to determine the
advertised flow control capability. The valid values are:
.RS
.TP
.B 0
flow control autonegotiation disabled (default)
.TP
.B 1
flow control autonegotiation enabled with capability specified in
\fBrx_flow_control\fP and \fBtx_flow_control\fP (only valid if \fBline_speed\fP
is set to \fB0\fP or \fBauto_speed\fP is set to \fB1\fP)
.TP
.B tx_pkt_desc_cnt
Configures the number of transmit descriptors. Default is 64. The
valid range is from 1 to 511.
.TP
.B rx_pkt_desc_cnt
Configures the number of receive descriptors. Default
is 64. The valid range is from 1 to 511.
.TP
.B enable_wol
Enables or disables magic packet Wake-On-LAN when the system is shutdown.
Note that not all systems support Wake-On-LAN. The valid values are:
.RS
.TP
.B 0
magic packet Wake-On-LAN disabled (default)
.TP
.B 1
magic packet Wake-On-LAN enabled
.RE
.TP
.\"
.\" DRIVER MESSAGES part
.\"
.SH DRIVER MESSAGES
The following are the most common sample messages that may be logged in the file
/var/log/messages. Use dmesg -n <level> to control the level at which messages
will appear on the console. Most systems are set to level 6 by default.
.PP
.B Broadcom 4401 Ethernet Driver bcm4400 ver. 2.0.0 (03/25/03)
.RS
Driver signon
.RE
.PP
.B eth#: Broadcom BCM4401 100Base-T found at mem f7ffc000, IRQ 18, node addr 0010180407b2
.RS
NIC detected
.RE
.PP
.B bcm4400: eth# NIC Link is Up, 100 Mbps full duplex
.RS
Link up and speed indication
.RE
.PP
.B bcm4400: eth# NIC Link is Down
.RS
 Link down indication
.RE
.\"
.\" FILES part
.\"
.SH FILES
.I /proc/net/nicinfo/eth#.info
.RS
Detailed statistics and configuration file.
.RE
.\"
.\" AUTHOR part
.\"
.SH AUTHOR
Michael Chan \- mchan@broadcom.com
.\"
.\" SEE ALSO part
.\"
.SH SEE ALSO
.BR ifconfig (8),
.BR insmod (8),
.BR modules.conf (5).

