# arch/ia64/sn/Makefile
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2003 Silicon Graphics, Inc.  All Rights Reserved.
#
# Makefile for the sn ia64 subplatform
#

obj-y += kernel/ io/
