#
# Makefile for m68knommu specific library files..
#

L_TARGET = lib.a
obj-y	:= ashldi3.o ashrdi3.o lshrdi3.o \
	   muldi3.o mulsi3.o divsi3.o udivsi3.o modsi3.o umodsi3.o \
	   checksum.o semaphore.o memcpy.o memset.o

include $(TOPDIR)/Rules.make
