
obj-$(CONFIG_IBM_ASM) := ibmasm.o

ibmasm-objs :=	module.o      \
		ibmasmfs.o    \
		event.o       \
		command.o     \
		remote.o      \
		heartbeat.o   \
		r_heartbeat.o \
		dot_command.o \
		lowlevel.o    \
		uart.o
