#
# Copyright (c) 2005-2006 Hewlett-Packard Development Company, L.P.
# Contributed by Stephane Eranian <eranian@hpl.hp.com>
#
obj-$(CONFIG_PERFMON)			+= perfmon.o
obj-$(CONFIG_IA64_PERFMON_COMPAT)	+= perfmon_default_smpl.o \
					   perfmon_compat.o
obj-$(CONFIG_IA64_PERFMON_GENERIC)	+= perfmon_generic.o
obj-$(CONFIG_IA64_PERFMON_ITANIUM)	+= perfmon_itanium.o
obj-$(CONFIG_IA64_PERFMON_MCKINLEY)	+= perfmon_mckinley.o
obj-$(CONFIG_IA64_PERFMON_MONTECITO)	+= perfmon_montecito.o
