#
# Makefile for the SGI arcs prom monitor library routines
# under Linux.
#

lib-y		+= console.o init.o memory.o tree.o env.o cmdline.o misc.o \
		   time.o file.o identify.o

lib-$(CONFIG_ARC_CONSOLE)   += arc_con.o
