#
# Copyright (c) 2005-2007 Hewlett-Packard Development Company, L.P.
# Contributed by Stephane Eranian <eranian@hpl.hp.com>
#
obj-$(CONFIG_PERFMON)			+= perfmon.o
obj-$(CONFIG_X86_PERFMON_P6)		+= perfmon_p6.o
obj-$(CONFIG_X86_PERFMON_P4)		+= perfmon_p4.o
obj-$(CONFIG_X86_PERFMON_CORE)		+= perfmon_intel_core.o
obj-$(CONFIG_X86_PERFMON_INTEL_ARCH)	+= perfmon_intel_arch.o
obj-$(CONFIG_X86_PERFMON_PEBS_P4)	+= perfmon_pebs_p4_smpl.o
obj-$(CONFIG_X86_PERFMON_PEBS_CORE)	+= perfmon_pebs_core_smpl.o
obj-$(CONFIG_X86_PERFMON_AMD64)   	+= perfmon_amd64.o
obj-$(CONFIG_X86_PERFMON_INTEL_ATOM)	+= perfmon_intel_atom.o
