# Makefile for the Linux device tree

obj-y		:= core.o sys.o interface.o power.o bus.o \
			driver.o class.o intf.o

obj-y		+= fs/

export-objs	:= core.o power.o sys.o bus.o driver.o \
			class.o intf.o

include $(TOPDIR)/Rules.make
