obj-y	+= toshiba_rbtx4927_prom.o 
obj-y	+= toshiba_rbtx4927_setup.o 
obj-y	+= toshiba_rbtx4927_irq.o 

obj-$(CONFIG_PCI)	+= toshiba_rbtx4927_pci_fixup.o 
obj-$(CONFIG_PCI)	+= toshiba_rbtx4927_pci_ops.o 

EXTRA_AFLAGS := $(CFLAGS)
