#
# Makefile for Linux arch/m68k/mac source directory
#

export-objs	:= mac_ksyms.o

obj-y		:= config.o bootparse.o macints.o iop.o via.o oss.o psc.o \
			baboon.o macboing.o debug.o misc.o mac_ksyms.o

include $(TOPDIR)/Rules.make
