dkmstree := drivers/gpu/drm/amd/dkms
srctree := $(subst /$(dkmstree),,$(realpath $(dir $(lastword $(MAKEFILE_LIST)))))

srcarch := $(shell uname -m | sed -e "s/i.86/x86/" -e "s/x86_64/x86/" \
	-e "s/sun4u/sparc64/" -e "s/arm.*/arm/" -e "s/sa110/arm/" \
	-e "s/s390x/s390/" -e "s/parisc64/parisc/" \
	-e "s/ppc.*/powerpc/" -e "s/mips.*/mips/" \
	-e "s/sh[234].*/sh/" -e "s/aarch64.*/arm64/")

userinclude := \
	-I$(srctree)/arch/$(srcarch)/include/uapi \
	-I$(srctree)/arch/$(srcarch)/include/generated/uapi \
	-I$(srctree)/include/uapi \
	-I$(srctree)/include/generated/uapi \
	-include $(srctree)/include/linux/kconfig.h

linuxinclude := \
	-I$(srctree)/arch/$(srcarch)/include \
	-I$(srctree)/arch/$(srcarch)/include/generated \
	-I$(srctree)/include \
	$(userinclude)

all: config clean

config: force
	@( \
		cd $(srctree)/$(dkmstree); \
		./autogen.sh; \
		CPPFLAGS="$(linuxinclude)" ./configure \
			--enable-linux-builtin \
			--with-linux=$(srctree) \
	)

clean: force
	@( \
		cd $(srctree)/$(dkmstree); \
		rm -f aclocal.m4 config.* configure config/*.in* \
	)

.PHONY: all force
