#!/bin/bash

KCL="amd/amdkcl"
INC="include"
SRC="amd/dkms"

KERNELVER=$1
KERNELVER_BASE=${KERNELVER%%-*}
SRCTREE=/lib/modules/$KERNELVER

if [ -L $SRCTREE/source ]; then
	BLDTREE="$SRCTREE/build"
	SRCTREE="$SRCTREE/source"
else
	SRCTREE="$SRCTREE/build"
	BLDTREE="$SRCTREE"
fi

SRCARCH=$(uname -m | sed -e "s/i.86/x86/" -e "s/x86_64/x86/" \
        -e "s/sun4u/sparc64/" -e "s/arm.*/arm/" -e "s/sa110/arm/" \
        -e "s/s390x/s390/" -e "s/parisc64/parisc/" \
        -e "s/ppc.*/powerpc/" -e "s/mips.*/mips/" \
        -e "s/sh[234].*/sh/" -e "s/aarch64.*/arm64/")

version_lt () {
    newest=$((echo "$KERNELVER_BASE"; echo "$1") | sort -V | tail -n1)
    [ "$KERNELVER_BASE" != "$newest" ]
}

version_ge () {
    newest=$((echo "$KERNELVER_BASE"; echo "$1") | sort -V | tail -n1)
    [ "$KERNELVER_BASE" = "$newest" ]
}

version_gt () {
    oldest=$((echo "$KERNELVER_BASE"; echo "$1") | sort -V | head -n1)
    [ "$KERNELVER_BASE" != "$oldest" ]
}

version_le () {
    oldest=$((echo "$KERNELVER_BASE"; echo "$1") | sort -V | head -n1)
    [ "$KERNELVER_BASE" = "$oldest" ]
}

source $KCL/symbols
source $KCL/files

echo '// auto generated by DKMS pre-build.sh' > $KCL/symbols.c
for sym in $SYMS; do
    addr=$(grep "\<$sym\>" /boot/System.map-$KERNELVER | awk -F' ' '{print $1}')
    echo "void *_kcl_$sym = (void *)0x$addr;" >> $KCL/symbols.c
done

while read line; do
	from_header=$(echo $line | cut -d ' ' -f 1)
	to_header=$(echo $line | cut -d ' ' -f 2)
	[ x$from_header = x ] && break
	from_header=$(echo "$from_header" | sed 's|\.h|\\&|')
	for file in `grep -rl ${from_header} amd/* scheduler/* ttm/* include/drm/* include/linux/* include/uapi/*`; do
		sed -i "s|${from_header}|${to_header}|" $file
	done
done < $SRC/headers

for file in $FILES; do
	grep EXPORT_SYMBOL $file \
		| sort -u \
		| awk -F'[()]' '{print "#define "$2" amd"$2" //"$0}'\
		>> $INC/rename_symbol.h
done

export KERNELVER
(cd $SRC && CPPFLAGS="-I$SRCTREE/arch/$SRCARCH/include \
	-I$BLDTREE/arch/$SRCARCH/include/generated \
	-I$SRCTREE/include \
	-I$BLDTREE/include \
	-I$SRCTREE/include/uapi \
	-include $SRCTREE/include/linux/kconfig.h" \
	./configure)
