#
# Makefile for the Linux/M32R driver
#

obj-$(CONFIG_M32R_SMC91111)	+= smc91111.o
obj-$(CONFIG_M32R_NE2000)	+= mappi_ne.o 8390.o
obj-$(CONFIG_M32RPCC)		+= m32r_pcc.o
obj-$(CONFIG_M32R_CFC)		+= m32r_cfc.o
obj-$(CONFIG_M32700UT_DS1302)	+= ds1302.o
