#
# Makefile for the Linux/MIPS-specific parts of the memory manager.
#

obj-$(CONFIG_CPU_TX49XX)	+= tlbex-r4k.o
obj-$(CONFIG_CPU_R4300)		+= tlbex-r4k.o
obj-$(CONFIG_CPU_R4X00)		+= tlbex-r4k.o
obj-$(CONFIG_CPU_VR41XX)	+= tlbex-r4k.o
obj-$(CONFIG_CPU_R5000)		+= tlbex-r4k.o
obj-$(CONFIG_CPU_NEVADA)	+= tlbex-r4k.o
obj-$(CONFIG_CPU_R5432)		+= tlbex-r4k.o
obj-$(CONFIG_CPU_RM7000)	+= tlbex-r4k.o
obj-$(CONFIG_CPU_RM9000)	+= tlbex-r4k.o
obj-$(CONFIG_CPU_R10000)	+= tlbex-r4k.o
obj-$(CONFIG_CPU_MIPS32)	+= tlbex-r4k.o
obj-$(CONFIG_CPU_MIPS64)	+= tlbex-r4k.o
obj-$(CONFIG_CPU_SB1)		+= tlbex-r4k.o

EXTRA_AFLAGS := $(CFLAGS)
