#
# Makefile for all Linux ACPI interpreter subdirectories
#

obj-y := dsfield.o   dsmthdat.o  dsopcode.o  dswexec.o  dswscope.o \
	 dsmethod.o  dsobject.o  dsutils.o   dswload.o  dswstate.o

EXTRA_CFLAGS += $(ACPI_CFLAGS)

include $(TOPDIR)/Rules.make
