#
# Makefile for USB Scanner drivers
#

O_TARGET	:= usb-scanner.o

obj-$(CONFIG_USB_HPUSBSCSI)	+= hpusbscsi.o
obj-$(CONFIG_USB_MICROTEK)	+= microtek.o
obj-$(CONFIG_USB_SCANNER)	+= scanner.o

include $(TOPDIR)/Rules.make
