#
#  Copyright 2000 MontaVista Software Inc.
#  Author: MontaVista Software, Inc.
#     	ppopov@mvista.com or source@mvista.com
#
# Makefile for the Galileo EV96100 board.
#

obj-y		+= init.o time.o irq.o int-handler.o setup.o puts.o

EXTRA_AFLAGS := $(CFLAGS)
