#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by arch/ppc64/Makefile
 *
 */

#define THREAD_SHIFT 14 /* THREAD_SHIFT */
#define THREAD_SIZE 16384 /* THREAD_SIZE */
#define TI_FLAGS 16 /* offsetof(struct thread_info, flags) */
#define THREAD 1328 /* offsetof(struct task_struct, thread) */
#define PT_REGS 8 /* offsetof(struct thread_struct, regs) */
#define THREAD_FPEXC_MODE 288 /* offsetof(struct thread_struct, fpexc_mode) */
#define THREAD_FPR0 24 /* offsetof(struct thread_struct, fpr[0]) */
#define THREAD_FPSCR 280 /* offsetof(struct thread_struct, fpscr) */
#define KSP 0 /* offsetof(struct thread_struct, ksp) */
#define THREAD_VR0 320 /* offsetof(struct thread_struct, vr[0]) */
#define THREAD_VRSAVE 848 /* offsetof(struct thread_struct, vrsave) */
#define THREAD_VSCR 832 /* offsetof(struct thread_struct, vscr) */
#define THREAD_USED_VR 856 /* offsetof(struct thread_struct, used_vr) */
#define MM 184 /* offsetof(struct task_struct, mm) */
#define PACA 24 /* offsetof(struct naca_struct, paca) */
#define DCACHEL1LINESIZE 100 /* offsetof(struct systemcfg, dCacheL1LineSize) */
#define DCACHEL1LOGLINESIZE 96 /* offsetof(struct naca_struct, dCacheL1LogLineSize) */
#define DCACHEL1LINESPERPAGE 100 /* offsetof(struct naca_struct, dCacheL1LinesPerPage) */
#define ICACHEL1LINESIZE 108 /* offsetof(struct systemcfg, iCacheL1LineSize) */
#define ICACHEL1LOGLINESIZE 104 /* offsetof(struct naca_struct, iCacheL1LogLineSize) */
#define ICACHEL1LINESPERPAGE 108 /* offsetof(struct naca_struct, iCacheL1LinesPerPage) */
#define SLBSIZE 72 /* offsetof(struct naca_struct, slb_size) */
#define PLATFORM 24 /* offsetof(struct systemcfg, platform) */
#define PACA_SIZE 8192 /* sizeof(struct paca_struct) */
#define PACAPACAINDEX 24 /* offsetof(struct paca_struct, xPacaIndex) */
#define PACAPROCSTART 256 /* offsetof(struct paca_struct, xProcStart) */
#define PACAKSAVE 32 /* offsetof(struct paca_struct, xKsave) */
#define PACACURRENT 16 /* offsetof(struct paca_struct, xCurrent) */
#define PACASAVEDMSR 2144 /* offsetof(struct paca_struct, xSavedMsr) */
#define PACASTABREAL 56 /* offsetof(struct paca_struct, xStab_data.real) */
#define PACASTABVIRT 64 /* offsetof(struct paca_struct, xStab_data.virt) */
#define PACASTABRR 72 /* offsetof(struct paca_struct, xStab_data.next_round_robin) */
#define PACAR1 2136 /* offsetof(struct paca_struct, xR1) */
#define PACALPQUEUE 40 /* offsetof(struct paca_struct, lpQueuePtr) */
#define PACATOC 48 /* offsetof(struct paca_struct, xTOC) */
#define PACAEXCSP 80 /* offsetof(struct paca_struct, exception_sp) */
#define PACAPROCENABLED 88 /* offsetof(struct paca_struct, xProcEnabled) */
#define PACADEFAULTDECR 28 /* offsetof(struct paca_struct, default_decr) */
#define PACAPROFENABLED 89 /* offsetof(struct paca_struct, prof_enabled) */
#define PACAPROFLEN 200 /* offsetof(struct paca_struct, prof_len) */
#define PACAPROFSHIFT 180 /* offsetof(struct paca_struct, prof_shift) */
#define PACAPROFBUFFER 184 /* offsetof(struct paca_struct, prof_buffer) */
#define PACAPROFSTEXT 192 /* offsetof(struct paca_struct, prof_stext) */
#define PACALPPACA 384 /* offsetof(struct paca_struct, xLpPaca) */
#define LPPACA 384 /* offsetof(struct paca_struct, xLpPaca) */
#define PACAREGSAV 1024 /* offsetof(struct paca_struct, xRegSav) */
#define PACAEXC 3840 /* offsetof(struct paca_struct, exception_stack) */
#define PACAGUARD 4096 /* offsetof(struct paca_struct, guard) */
#define LPPACASRR0 144 /* offsetof(struct ItLpPaca, xSavedSrr0) */
#define LPPACASRR1 152 /* offsetof(struct ItLpPaca, xSavedSrr1) */
#define LPPACAANYINT 128 /* offsetof(struct ItLpPaca, xIntDword.xAnyInt) */
#define LPPACADECRINT 132 /* offsetof(struct ItLpPaca, xIntDword.xFields.xDecrInt) */
#define LPQCUREVENTPTR 16 /* offsetof(struct ItLpQueue, xSlicCurEventPtr) */
#define LPQOVERFLOW 0 /* offsetof(struct ItLpQueue, xPlicOverflowIntPending) */
#define LPEVENTFLAGS 0 /* offsetof(struct HvLpEvent, xFlags) */
#define PROMENTRY 0 /* offsetof(struct prom_t, entry) */
#define RTASBASE 8 /* offsetof(struct rtas_t, base) */
#define RTASENTRY 0 /* offsetof(struct rtas_t, entry) */
#define RTASSIZE 16 /* offsetof(struct rtas_t, size) */
#define STACK_FRAME_OVERHEAD 112 /* STACK_FRAME_OVERHEAD */
#define SWITCH_FRAME_SIZE 464 /* STACK_FRAME_OVERHEAD + sizeof(struct pt_regs) */
#define INT_FRAME_SIZE 752 /* STACK_FRAME_OVERHEAD + sizeof(struct pt_regs) + 288 */
#define PROM_FRAME_SIZE 480 /* STACK_FRAME_OVERHEAD + sizeof(struct pt_regs) + 16 */
#define RTAS_FRAME_SIZE 480 /* STACK_FRAME_OVERHEAD + sizeof(struct pt_regs) + 16 */
#define GPR0 112 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[0]) */
#define GPR1 120 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[1]) */
#define GPR2 128 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[2]) */
#define GPR3 136 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[3]) */
#define GPR4 144 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[4]) */
#define GPR5 152 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[5]) */
#define GPR6 160 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[6]) */
#define GPR7 168 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[7]) */
#define GPR8 176 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[8]) */
#define GPR9 184 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[9]) */
#define GPR20 272 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[20]) */
#define GPR21 280 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[21]) */
#define GPR22 288 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[22]) */
#define GPR23 296 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, gpr[23]) */
#define _NIP 368 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, nip) */
#define _MSR 376 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, msr) */
#define _CTR 392 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, ctr) */
#define _LINK 400 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, link) */
#define _CCR 416 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, ccr) */
#define _XER 408 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, xer) */
#define _DAR 440 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, dar) */
#define _DSISR 448 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, dsisr) */
#define ORIG_GPR3 384 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, orig_gpr3) */
#define RESULT 456 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, result) */
#define TRAP 432 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, trap) */
#define SOFTE 424 /* STACK_FRAME_OVERHEAD+offsetof(struct pt_regs, softe) */
#define _SRR0 464 /* STACK_FRAME_OVERHEAD+sizeof(struct pt_regs) */
#define _SRR1 472 /* STACK_FRAME_OVERHEAD+sizeof(struct pt_regs)+8 */
#define CLONE_VM 256 /* CLONE_VM */
#define CLONE_UNTRACED 8388608 /* CLONE_UNTRACED */
#define CPU_SPEC_ENTRY_SIZE 56 /* sizeof(struct cpu_spec) */
#define CPU_SPEC_PVR_MASK 0 /* offsetof(struct cpu_spec, pvr_mask) */
#define CPU_SPEC_PVR_VALUE 4 /* offsetof(struct cpu_spec, pvr_value) */
#define CPU_SPEC_FEATURES 16 /* offsetof(struct cpu_spec, cpu_features) */
#define CPU_SPEC_SETUP 40 /* offsetof(struct cpu_spec, cpu_setup) */

#endif
