#ifndef AMDGPU_BACKPORT_H
#define AMDGPU_BACKPORT_H

#include <linux/version.h>
#include "kcl/kcl_backport_amdgpu.h"
#include <kcl/kcl_mn.h>
#include <kcl/reservation.h>
#include <kcl/kcl_drm_print.h>
#include <kcl/kcl_fs.h>
#include <kcl/kcl_amdgpu.h>
#include <kcl/kcl_drm_backport.h>
#include <kcl/kcl_acpi.h>
#include <kcl/kcl_bitops.h>
#include <kcl/kcl_device.h>
#include <kcl/kcl_device_cgroup_backport.h>
#include <kcl/kcl_kref.h>
#include <kcl/kcl_drm_atomic_helper.h>
#include <kcl/kcl_drm_cache.h>
#include <kcl/kcl_drm_connector.h>
#include <kcl/kcl_drm_dp_helper_backport.h>
#include <kcl/kcl_drm_vma_manager_backport.h>
#include <kcl/kcl_fence_backport.h>
#include <kcl/kcl_firmware.h>
#include <kcl/kcl_hwmon.h>
#include <kcl/kcl_interval_tree_generic.h>
#include <kcl/kcl_io.h>
#include <kcl/kcl_kernel.h>
#include <kcl/kcl_kthread_backport.h>
#include <kcl/kcl_mm_backport.h>
#include <kcl/kcl_mmu_notifier.h>
#include <kcl/kcl_suspend.h>
#include <kcl/kcl_pagemap.h>
#include <kcl/kcl_pci_backport.h>
#include <kcl/kcl_perf_event_backport.h>
#include <kcl/kcl_suspend.h>
#include <kcl/kcl_timekeeping.h>
#include <kcl/kcl_uaccess_backport.h>
#endif /* AMDGPU_BACKPORT_H */
