#
# Makefile for ALSA
# Copyright (c) 2001 by Jaroslav Kysela <perex@suse.cz>
#

O_TARGET     := _korg1212.o

snd-korg1212-objs := korg1212.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_KORG1212) += snd-korg1212.o

include $(TOPDIR)/Rules.make
