#
# drivers/char/pcmcia/Makefile
#
# Makefile for the Linux PCMCIA char device drivers.
#

obj-$(CONFIG_PCMCIA_SERIAL_CS)	+= serial_cs.o
obj-$(CONFIG_SYNCLINK_CS) += synclink_cs.o

include $(TOPDIR)/Rules.make
