/* This file is automatically generated.  Do not edit. */
/*
 * Security object class definitions
 */
static char *class_to_string[] =
{
    "null",
    "security",
    "process",
    "system",
    "capability",
    "filesystem",
    "file",
    "dir",
    "fd",
    "lnk_file",
    "chr_file",
    "blk_file",
    "sock_file",
    "fifo_file",
    "socket",
    "tcp_socket",
    "udp_socket",
    "rawip_socket",
    "node",
    "netif",
    "netlink_socket",
    "packet_socket",
    "key_socket",
    "unix_stream_socket",
    "unix_dgram_socket",
    "sem",
    "msg",
    "msgq",
    "shm",
    "ipc",
    "passwd",
};

