#
# Makefile for ALSA
# Copyright (c) 2001 by Jaroslav Kysela <perex@suse.cz>
#

snd-vxpocket-objs := vxpocket.o vx_entry.o vxp_ops.o vxp_mixer.o
snd-vxp440-objs := vxpocket.o vx_entry.o vxp_ops.o vxp_mixer.o

obj-$(CONFIG_SND_VXPOCKET) += snd-vxpocket.o
obj-$(CONFIG_SND_VXP440) += snd-vxp440.o
