#
# Makefile for the generic architecture
#

EXTRA_CFLAGS	+= -I../kernel

obj-y				:= probe.o summit.o bigsmp.o default.o


#
# Makefile for the generic architecture
#

EXTRA_CFLAGS	+= -I../kernel

obj-y				:= probe.o summit.o bigsmp.o default.o


