#
# Makefile for the FPU instruction emulation.
#

obj-$(CONFIG_MATHEMU) := math.o qrnnd.o

EXTRA_CFLAGS = -I. -I$(TOPDIR)/include/math-emu -w
EXTRA_AFLAGS	:= -traditional

include $(TOPDIR)/Rules.make


