#
# Makefile for Momentum Computer's Ocelot-C and -CS boards.
#

obj-y	 		+= mv-irq.o cpci-irq.o uart-irq.o int-handler.o irq.o \
			   pci-irq.o prom.o reset.o setup.o 

obj-$(CONFIG_KGDB)	+= dbg_io.o
