#
# Makefile for the kernel DVB device drivers.
#

dvb-core-objs = dvbdev.o dmxdev.o dvb_demux.o dvb_filter.o \
		dvb_functions.o dvb_frontend.o dvb_i2c.o dvb_net.o dvb_ksyms.o dvb_ringbuffer.o

obj-$(CONFIG_DVB_CORE) += dvb-core.o
