# arch/ia64/sn/io/Makefile
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2000-2002 Silicon Graphics, Inc.  All Rights Reserved.
#
# Makefile for the sn io routines.
#

EXTRA_CFLAGS    := -DLITTLE_ENDIAN

obj-y += sgi_if.o xswitch.o sgi_io_sim.o cdl.o \
	 io.o machvec/ drivers/ platform_init/ sn2/ hwgfs/
