sfc-y			+= efx.o falcon.o tx.o rx.o falcon_xmac.o \
			   selftest.o ethtool.o xfp_phy.o \
			   mdio_10g.o tenxpress.o boards.o sfe4001.o
sfc-$(CONFIG_SFC_DRIVERLINK) += driverlink.o
obj-$(CONFIG_SFC)	+= sfc.o

obj-$(CONFIG_SFC_RESOURCE) += sfc_resource/
