obj-$(CONFIG_PARAVIRT_XEN)	+= grant-table.o

obj-y	+= core/
obj-y	+= console/
obj-y	+= evtchn/
obj-y	+= xenbus/
obj-y	+= gntdev/
obj-y	+= char/

obj-y	+= util.o
obj-$(CONFIG_XEN_BALLOON)		+= balloon/
obj-$(CONFIG_XEN_BLKDEV_BACKEND)	+= blkback/
obj-$(CONFIG_XEN_BLKDEV_TAP)		+= blktap/
obj-$(CONFIG_XEN_NETDEV_BACKEND)	+= netback/
obj-$(CONFIG_XEN_TPMDEV_BACKEND)	+= tpmback/
obj-$(CONFIG_XEN_BLKDEV_FRONTEND)	+= blkfront/
obj-$(CONFIG_XEN_NETDEV_FRONTEND)	+= netfront/
obj-$(CONFIG_XEN_PCIDEV_BACKEND)	+= pciback/
obj-$(CONFIG_XEN_PCIDEV_FRONTEND)	+= pcifront/
obj-$(CONFIG_XEN_FRAMEBUFFER)		+= fbfront/
obj-$(CONFIG_XEN_KEYBOARD)		+= fbfront/
obj-$(CONFIG_XEN_PRIVCMD)	+= privcmd/
