#
# Makefile for drivers/net/tokenring
#

export-objs := tms380tr.o

obj-$(CONFIG_IBMTR) 	+= ibmtr.o
obj-$(CONFIG_IBMOL) 	+= olympic.o
obj-$(CONFIG_IBMLS) 	+= lanstreamer.o
obj-$(CONFIG_TMS380TR) 	+= tms380tr.o
obj-$(CONFIG_ABYSS) 	+= abyss.o
obj-$(CONFIG_MADGEMC) 	+= madgemc.o
obj-$(CONFIG_TMSPCI) 	+= tmspci.o
obj-$(CONFIG_TMSISA) 	+= tmsisa.o
obj-$(CONFIG_SMCTR) 	+= smctr.o
obj-$(CONFIG_3C359)	+= 3c359.o

include $(TOPDIR)/Rules.make
