#!/bin/sh
#
# Copyright (C) 2002 Khalid Aziz <khalid_aziz@hp.com>
# Copyright (C) 2002 Randy Dunlap <rddunlap@osdl.org>
# Copyright (C) 2002 Al Stone <ahs3@fc.hp.com>
# Copyright (C) 2002 Hewlett-Packard Company
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# 
# Rules to generate ikconfig.h from linux/.config:
#	- Retain lines that begin with "CONFIG_"
#	- Retain lines that begin with "# CONFIG_"
#	- lines that use double-quotes must \\-escape-quote them

if [ $# -lt 2 ]
then
	echo "Usage: `basename $0` <configuration_file> <Makefile>"
	exit 1
fi

config=$1
makefile=$2

echo "#ifndef _IKCONFIG_H"
echo "#define _IKCONFIG_H"
echo \
"/*
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, GOOD TITLE or
 * NON INFRINGEMENT.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 *
 * 
 * This file is generated automatically by scripts/mkconfigs. Do not edit.
 *
 */"

echo "static char const ikconfig_config[] __attribute__((unused)) = "
echo "\"CONFIG_BEGIN=n\\n\\"
echo "`cat $config | sed 's/\"/\\\\\"/g' | grep "^#\? \?CONFIG_" | awk '{ print $0 "\\\\n\\\\" }' `"
echo "CONFIG_END=n\\n\";"
echo "#endif /* _IKCONFIG_H */"
