#!/bin/sh
# Generates a small Makefile used in the root of the output
# directory, to allow make to be started from there.
# The Makefile also allow for more convinient build of external modules

# Usage
# $1 - Kernel src directory
# $2 - Output directory


cat << EOF

KERNELSRC    := $1
KERNELOUTPUT := $2

MAKEFLAGS += --no-print-directory

all:
	\$(MAKE) -C \$(KERNELSRC) O=\$(KERNELOUTPUT)

%::
	\$(MAKE) -C \$(KERNELSRC) O=\$(KERNELOUTPUT) \$@

EOF

