# Makefile for the icn ISDN device driver

# The target object and module list name.

O_TARGET	:= built-in.o

# Each configuration option enables a list of files.

obj-$(CONFIG_ISDN_DRV_ICN)	+= icn.o

include $(TOPDIR)/Rules.make
