#
# Makefile for the kernel hardware sensors bus drivers.
#

obj-$(CONFIG_I2C_ALI15X3)	+= i2c-ali15x3.o
obj-$(CONFIG_I2C_AMD756)	+= i2c-amd756.o
obj-$(CONFIG_I2C_AMD8111)	+= i2c-amd8111.o
obj-$(CONFIG_I2C_I801)		+= i2c-i801.o
obj-$(CONFIG_I2C_ISA)		+= i2c-isa.o
obj-$(CONFIG_I2C_PIIX4)		+= i2c-piix4.o
