obj-$(CONFIG_X86_POWERNOW_K6)	+= powernow-k6.o
obj-$(CONFIG_X86_LONGHAUL)	+= longhaul.o
obj-$(CONFIG_X86_SPEEDSTEP)	+= speedstep.o
obj-$(CONFIG_X86_P4_CLOCKMOD)	+= p4-clockmod.o
obj-$(CONFIG_ELAN_CPUFREQ)	+= elanfreq.o
obj-$(CONFIG_X86_LONGRUN)	+= longrun.o  

include $(TOPDIR)/Rules.make
