#
# Makefile for parisc-specific library files..
#

USE_STANDARD_AS_RULE := true

L_TARGET = lib.a

obj-y := lusercopy.o bitops.o checksum.o

EXTRA_AFLAGS := -traditional

include $(TOPDIR)/Rules.make
