# arch/ia64/sn/io/sn2/pcibr/Makefile
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 2002-2003 Silicon Graphics, Inc.  All Rights Reserved.
#
# Makefile for the sn2 specific pci bridge routines.
#

obj-y += pcibr_ate.o pcibr_config.o \
	 pcibr_dvr.o pcibr_hints.o  \
	 pcibr_intr.o pcibr_rrb.o   \
	 pcibr_slot.o pcibr_error.o \
	 pcibr_reg.o 
