#
# Makefile for common code for Toshiba TX4927 based systems
#

obj-y	:= tx4927_prom.o
obj-y	+= tx4927_setup.o
obj-y	+= tx4927_irq.o
obj-y	+= tx4927_irq_handler.o

obj-$(CONFIG_KGDB)                 += tx4927_dbgio.o
