#
# Makefile for the linux arm26-specific parts of the memory manager.
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definition is now in the main makefile...

# Object file lists.

obj-y		:= init.o extable.o proc-funcs.o mm-memc.o fault.o
