#
# Makefile for ALSA
# Copyright (c) 2001 by Jaroslav Kysela <perex@suse.cz>
#

O_TARGET     := _nm256.o

snd-nm256-objs := nm256.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_NM256) += snd-nm256.o

include $(TOPDIR)/Rules.make
