#
# Makefile for the 'link_service' sub-component of DAL.
# It provides the functionality for display port SST, MST. 


LINK_SERVICE = link_service.o dpsst_link_service.o

AMD_DAL_LINK_SERVICE = $(addprefix $(AMDDALPATH)/link_service/,$(LINK_SERVICE))

AMD_DAL_FILES += $(AMD_DAL_LINK_SERVICE)
