#
# Makefile 1.00 Peter Braam <braam@clusterfs.com>
#

obj-$(CONFIG_INTERMEZZO_FS) += intermezzo.o

intermezzo-objs := cache.o dcache.o dir.o ext_attr.o file.o fileset.o \
	           inode.o journal.o journal_ext2.o journal_ext3.o \
	           journal_obdfs.o journal_reiserfs.o journal_tmpfs.o journal_xfs.o \
	           kml_reint.o kml_unpack.o methods.o presto.o psdev.o replicator.o \
	           super.o sysctl.o upcall.o vfs.o
