
obj-$(CONFIG_BLK_DEV_MPC8xx_IDE)	+= mpc8xx.o
obj-$(CONFIG_BLK_DEV_IDE_PMAC)		+= pmac.o
obj-$(CONFIG_BLK_DEV_IDE_SWARM)		+= swarm.o
obj-$(CONFIG_BLK_DEV_IDE_STB04xxx)	+= ibm_ocp_ide.o

EXTRA_CFLAGS	:= -Idrivers/ide
