#
# Makefile for all Linux ACPI interpreter subdirectories
#

obj-y := rsaddr.o  rscreate.o  rsio.o   rslist.o    rsmisc.o   rsxface.o \
	 rscalc.o  rsdump.o    rsirq.o  rsmemory.o  rsutils.o

EXTRA_CFLAGS += $(ACPI_CFLAGS)
