#
# Makefile for the SGI specific kernel interface routines
# under Linux.
#

obj-y	+= ip32-berr.o ip32-rtc.o ip32-setup.o ip32-irq.o ip32-irq-glue.o \
	   ip32-timer.o crime.o ip32-reset.o

EXTRA_AFLAGS := $(CFLAGS)
